// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/auditoria" | "/admin/avarias" | "/admin/categorias" | "/admin/clientes" | "/admin/comprovante-comissao/[id]" | "/admin/configuracao" | "/admin/criar-pedido" | "/admin/financeiro" | "/admin/minhas-comissoes" | "/admin/pedidos" | "/admin/produtos" | "/admin/usuarios" | "/area-cliente/login" | "/area-cliente/minha-conta" | "/carnet/[id]" | "/carnet/[id]/[installmentNumber]" | "/checkout" | "/login" | "/order-confirmation/[id]" | "/produtos/[id]"
type AppRouteHandlerRoutes = "/api/asaas/pix" | "/api/asaas/webhook" | "/api/audit/log" | "/api/audit/logs" | "/api/ip" | "/api/public/categories" | "/api/public/products"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/carnet" | "/login"
type RedirectRoutes = never
type RewriteRoutes = "/@vite/client"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/@vite/client": {}
  "/admin": {}
  "/admin/auditoria": {}
  "/admin/avarias": {}
  "/admin/categorias": {}
  "/admin/clientes": {}
  "/admin/comprovante-comissao/[id]": { "id": string; }
  "/admin/configuracao": {}
  "/admin/criar-pedido": {}
  "/admin/financeiro": {}
  "/admin/minhas-comissoes": {}
  "/admin/pedidos": {}
  "/admin/produtos": {}
  "/admin/usuarios": {}
  "/api/asaas/pix": {}
  "/api/asaas/webhook": {}
  "/api/audit/log": {}
  "/api/audit/logs": {}
  "/api/ip": {}
  "/api/public/categories": {}
  "/api/public/products": {}
  "/area-cliente/login": {}
  "/area-cliente/minha-conta": {}
  "/carnet": {}
  "/carnet/[id]": { "id": string; }
  "/carnet/[id]/[installmentNumber]": { "id": string; "installmentNumber": string; }
  "/checkout": {}
  "/login": {}
  "/order-confirmation/[id]": { "id": string; }
  "/produtos/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/carnet": never
  "/login": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
