// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/(public)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auditoria">> = Specific
  const handler = {} as typeof import("../../src/app/admin/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/avarias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/avarias">> = Specific
  const handler = {} as typeof import("../../src/app/admin/avarias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/categorias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/categorias">> = Specific
  const handler = {} as typeof import("../../src/app/admin/categorias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/clientes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/clientes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/clientes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/comprovante-comissao/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/comprovante-comissao/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/admin/comprovante-comissao/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/configuracao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/configuracao">> = Specific
  const handler = {} as typeof import("../../src/app/admin/configuracao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/criar-pedido/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/criar-pedido">> = Specific
  const handler = {} as typeof import("../../src/app/admin/criar-pedido/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/financeiro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/financeiro">> = Specific
  const handler = {} as typeof import("../../src/app/admin/financeiro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/minhas-comissoes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/minhas-comissoes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/minhas-comissoes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/pedidos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/pedidos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/pedidos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/produtos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/produtos">> = Specific
  const handler = {} as typeof import("../../src/app/admin/produtos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/usuarios">> = Specific
  const handler = {} as typeof import("../../src/app/admin/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/area-cliente/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/area-cliente/login">> = Specific
  const handler = {} as typeof import("../../src/app/area-cliente/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/area-cliente/minha-conta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/area-cliente/minha-conta">> = Specific
  const handler = {} as typeof import("../../src/app/area-cliente/minha-conta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/carnet/[id]/[installmentNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carnet/[id]/[installmentNumber]">> = Specific
  const handler = {} as typeof import("../../src/app/carnet/[id]/[installmentNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/carnet/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/carnet/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/carnet/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/order-confirmation/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/order-confirmation/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/order-confirmation/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/produtos/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/produtos/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/produtos/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/avarias/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/avarias">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/avarias/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/commission-payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/commission-payments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/commission-payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/customers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/customers">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/customers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/monitoring/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/monitoring">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/monitoring/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/monitoring/summary/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/monitoring/summary">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/monitoring/summary/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/orders/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/orders">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/orders/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/permissions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/permissions">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/permissions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stock-audits/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stock-audits">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stock-audits/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/asaas/pix/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/asaas/pix">> = Specific
  const handler = {} as typeof import("../../src/app/api/asaas/pix/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/asaas/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/asaas/webhook">> = Specific
  const handler = {} as typeof import("../../src/app/api/asaas/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/log">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/audit/logs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/audit/logs">> = Specific
  const handler = {} as typeof import("../../src/app/api/audit/logs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/debug/supabase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/debug/supabase">> = Specific
  const handler = {} as typeof import("../../src/app/api/debug/supabase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/supabase/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health/supabase">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/supabase/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/ip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ip">> = Specific
  const handler = {} as typeof import("../../src/app/api/ip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/categories">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/public/products/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/public/products">> = Specific
  const handler = {} as typeof import("../../src/app/api/public/products/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/(public)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(public)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/carnet/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/carnet">> = Specific
  const handler = {} as typeof import("../../src/app/carnet/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
